### ISSUE TITLE
update_available_android - Namespace not specified

### ISSUE THREAD

**Issue by TheAndroidMonk** [mateusfccp/update_available#37]
Compilation fails on AGP 8.3.0
`Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@1da8d279 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':update_available_android'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
           If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.`

Request to migrate to latest AGP and gradle.

**Comment by kuhnroyal** [comment]
@TheAndroidMonk Can you test the linked PR?

**Comment by coder-flutter** [comment]
Can you please update the package as we are still getting the same error.

**Comment by mateusfccp** [comment]
> Can you please update the package as we are still getting the same error.

The proposed solution has been merged into `master`. We have a release prepared with this fix, so it would be helpful if you could test it, so we could be sure it's working as intended.

You can do it by pointing the dependency in your `pubspec.yaml` directly to `master`.

**Comment by kuhnroyal** [comment]
```yaml

dependency_overrides:
  update_available:
    git:
      url: https://github.com/mateusfccp/update_available
      ref: master
      path: update_available
  update_available_ios:
    git:
      url: https://github.com/mateusfccp/update_available
      ref: master
      path: update_available_ios
  update_available_android:
    git:
      url: https://github.com/mateusfccp/update_available
      ref: master
      path: update_available_android

```
